name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: check-circle
  color: blue

# Define your inputs here.
inputs:
  version:
    description: >
      The version or tag to check if a valid SemVer. Accepts '1.2.3', 'v1.2.3',
      and 'v1.2.3-beta.4'
    required: true
  token:
    description: >
      The GitHub token to use to access the GitHub API
    required: false
  repository:
    description: >
      Repository name with owner. For example, aisrael/check-semver. Defaults to
      the workflow's repository
    default: ${{ github.repository }}
  check_tags:
    description: >
      Set to "true" to check that this new version is SemVer higher than
      existing tags
    required: false
    default: 'true'
  check_releases:
    description: >
      Set to "true" to check that this new version is SemVer higher than
      existing releases
    required: false
    default: 'true'
  prefix:
    description: >
      An optional prefix to prepend to the SemVer. For example, "cli-"
    required: false
  suffix:
    description: >
      An optional suffix to append to the SemVer. For example "-hotfix"
    required: false

# Define your outputs here.
outputs:
  valid:
    description: >
      Whether the version is valid, and, is SemVer

runs:
  using: node20
  main: dist/index.js
